# permissions for end users to edit clusterconfigmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterconfigmap-editor-role
rules:
- apiGroups:
  - devhw.github.com
  resources:
  - clusterconfigmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devhw.github.com
  resources:
  - clusterconfigmaps/status
  verbs:
  - get
