# permissions for end users to view clusterconfigmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterconfigmap-viewer-role
rules:
- apiGroups:
  - devhw.github.com
  resources:
  - clusterconfigmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devhw.github.com
  resources:
  - clusterconfigmaps/status
  verbs:
  - get
