---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - devhw.github.com
  resources:
  - clusterconfigmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devhw.github.com
  resources:
  - clusterconfigmaps/finalizers
  verbs:
  - update
- apiGroups:
  - devhw.github.com
  resources:
  - clusterconfigmaps/status
  verbs:
  - get
  - patch
  - update
