apiVersion: devhw.github.com/v1
kind: ClusterConfigMap
metadata:
  name: ccm-test
spec:
  data:
    environment: "dev"
    foo: "blarg"
  generateTo:
    namespaceSelectors: 
      - matchLabels:
          app.kubernetes.io/managed-by: "dev-team"
      - matchLabels:
          app.kubernetes.io/managed-by: "infra-team"