apiVersion: devhw.github.com/v1
kind: ClusterConfigMap
metadata:
  name: ccm-test
spec:
  data:
    environment: "blargle"
  generateTo:
    namespaceSelectors: 
      - matchLabels:
          fnargle: "exists"
      - matchLabels:
          blagrle: "yup"
